# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a18cc3980fbb23c549a4006f9073244d781fcfcf863ab94005d9f8e7694cd5519c3eaf6737165fad606fbb1159904e83d786bd34abe85d1c06922e86d2bcc3

test:
  secret_key_base: a62b76e404f8d152d6289993fa9f3301ccba6d12c0e99053ff43af98ae9ff26e1350797017b18747ffe6c953b21db048c2a3cd8f182d9d9cbbba728001bc6e1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
